### ISSUE TITLE
Bug Navbar Inversione Esami - Lauree quando si clicca su Esami

### ISSUE THREAD

**Issue by beartice** [Alessandrostr95/PinkPeachProject#1]
Inizialmente la Navbar si presenta in questo modo:
![image](https://user-images.githubusercontent.com/46728229/131318788-90abbc93-e343-4fae-88ff-a40ae752da74.png)

Se pero' si clicca su Esami cambia l'ordine tra le tabs Esami e Lauree:
![image](https://user-images.githubusercontent.com/46728229/131318863-8cea754e-f874-4d9b-9741-4926d01cb7cb.png)

Ed inoltre, se si clicca sulla tab Lauree si va nella tab giusta, mentre se da qui provo a riandare nella tab Esami si rimane bloccati in Lauree. (Le altre tabs invece funzionano correttamente).

(Grazie per il sito fantastico tho)

**Comment by Alessandrostr95** [comment]
Ciao beartice,
abbiamo subito provveduto a risolvere. E' stato rigenerato il sito e caricato sul server, a breve saranno visibili le modifiche.
Grazie per il tuo contributo ;)
